<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<module category="EVA" descriptorversion="1.0" entrypoint="CFE_EVAFlujoAlterno/Start" forcesubdialogcall="false" frameworkversion="08.10.06.01" iconlarge="icons/defaultapplicationlg.gif" iconsmall="icons/defaultapplicationsm.gif" modifyInputs="false" modifyOutputs="false" nature="com.avaya.sce.core.speechnature" outputmultipart="false" paramasnamelist="false" provider="Reto" submitmethod="get" version="1.0.0" webname="CFE_EVAFlujoAlterno">
    <description/>
    <output defaultvalue="" description="" name="Estatus" varreftypesimple="true"/>
    <output defaultvalue="" description="" name="ID" varreftypesimple="true"/>
    <output defaultvalue="" description="" name="Mensaje" varreftypesimple="true"/>
    <language name="spanish" root="es-mx"/>
    <dependencies/>
</module>
